[package]
name = "quickshare"
version = "0.2.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-files = "0.6"
serde = { version = "1.0.228", features = ["derive"] }
qrcode = "0.14.1"
image = "0.25.9"
rand = "0.10.0"
show-image = "0.14.1"
actix-rt = "2.11.0"
interprocess = "2.4.0"
anyhow = "1.0.102"

[dependencies.windows]
version = "0.62.2"
features = [
    "Win32_Security",
    "Win32_System_Threading"
]
