name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release

      - name: Install Inno Setup
        run: choco install innosetup --no-progress

      - name: Compile installer
        run: |
          ISCC.exe ".\setup\setup.iss"

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            "setup/Output/quickshare setup.exe"
