name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Get version from Cargo.toml
        id: version
        shell: pwsh
        run: |
          $version = (Select-String -Path Cargo.toml -Pattern '^version\s*=\s*"(.*)"').Matches.Groups[1].Value
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT

      - name: Create tag if not exists
        shell: pwsh
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          $tag = "v${{ steps.version.outputs.VERSION }}"
          git fetch --tags
          if (-not (git tag -l $tag)) {
            git tag $tag
            git push origin $tag
          }

      - name: Build release binary
        run: cargo build --release

      - name: Install Inno Setup
        run: choco install innosetup --no-progress

      - name: Compile installer
        run: |
          ISCC.exe ".\setup\setup.iss"

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          files: |
            setup/Output/quickshare-setup.exe
          overwrite_files: true
